---
abstract: 'Manage Amazon Web Services credentials'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Spec: 3.31
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-Config
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  Net::Amazon::Config:
    file: lib/Net/Amazon/Config.pm
    version: 0.001
  Net::Amazon::Config::Profile:
    file: lib/Net/Amazon/Config/Profile.pm
    version: 0.001
requires:
  Carp: 0
  Config::Tiny: 2.12
  Object::Tiny: 1.06
  Params::Validate: 0.91
  Path::Class: 0.17
  constant: 1
  perl: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Amazon-Config
  repository: http://github.com/dagolden/Net-Amazon-Config/
version: 0.001
