---
abstract: 'Manage Amazon Web Services credentials'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0.88'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Amazon-Config
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Net::Amazon::Config:
    file: lib/Net/Amazon/Config.pm
    version: '0.002'
  Net::Amazon::Config::Profile:
    file: lib/Net/Amazon/Config/Profile.pm
    version: '0.002'
requires:
  Carp: '0'
  Config::Tiny: '2.12'
  Object::Tiny: '1.06'
  Params::Validate: '0.91'
  Path::Class: '0.17'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/Net-Amazon-Config/issues
  homepage: https://github.com/dagolden/Net-Amazon-Config
  repository: https://github.com/dagolden/Net-Amazon-Config.git
version: '0.002'
x_authority: cpan:DAGOLDEN
